workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Generate Android project files
        script: |
          cd mobile
          flutter create . --platforms=android
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter pub get
      - name: Build APK
        script: |
          cd mobile
          flutter build apk --debug
    artifacts:
      - mobile/build/**/outputs/**/*.apk
